insert into HABITACIONES (numero, tiposhabitacion_nombre) values (1, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (2, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (3, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (4, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (5, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (6, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (7, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (8, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (9, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (10, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (11, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (12, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (13, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (14, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (15, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (16, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (17, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (18, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (19, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (20, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (21, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (22, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (23, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (24, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (25, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (26, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (27, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (28, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (29, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (30, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (31, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (32, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (33, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (34, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (35, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (36, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (37, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (38, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (39, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (40, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (41, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (42, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (43, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (44, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (45, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (46, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (47, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (48, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (49, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (50, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (51, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (52, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (53, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (54, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (55, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (56, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (57, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (58, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (59, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (60, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (61, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (62, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (63, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (64, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (65, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (66, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (67, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (68, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (69, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (70, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (71, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (72, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (73, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (74, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (75, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (76, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (77, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (78, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (79, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (80, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (81, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (82, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (83, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (84, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (85, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (86, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (87, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (88, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (89, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (90, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (91, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (92, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (93, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (94, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (95, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (96, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (97, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (98, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (99, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (100, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (101, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (102, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (103, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (104, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (105, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (106, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (107, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (108, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (109, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (110, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (111, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (112, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (113, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (114, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (115, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (116, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (117, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (118, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (119, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (120, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (121, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (122, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (123, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (124, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (125, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (126, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (127, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (128, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (129, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (130, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (131, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (132, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (133, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (134, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (135, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (136, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (137, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (138, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (139, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (140, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (141, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (142, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (143, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (144, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (145, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (146, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (147, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (148, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (149, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (150, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (151, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (152, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (153, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (154, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (155, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (156, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (157, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (158, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (159, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (160, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (161, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (162, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (163, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (164, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (165, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (166, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (167, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (168, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (169, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (170, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (171, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (172, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (173, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (174, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (175, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (176, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (177, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (178, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (179, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (180, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (181, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (182, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (183, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (184, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (185, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (186, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (187, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (188, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (189, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (190, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (191, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (192, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (193, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (194, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (195, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (196, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (197, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (198, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (199, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (200, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (201, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (202, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (203, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (204, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (205, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (206, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (207, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (208, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (209, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (210, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (211, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (212, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (213, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (214, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (215, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (216, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (217, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (218, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (219, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (220, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (221, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (222, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (223, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (224, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (225, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (226, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (227, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (228, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (229, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (230, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (231, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (232, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (233, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (234, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (235, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (236, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (237, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (238, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (239, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (240, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (241, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (242, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (243, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (244, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (245, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (246, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (247, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (248, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (249, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (250, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (251, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (252, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (253, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (254, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (255, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (256, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (257, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (258, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (259, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (260, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (261, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (262, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (263, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (264, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (265, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (266, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (267, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (268, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (269, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (270, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (271, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (272, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (273, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (274, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (275, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (276, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (277, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (278, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (279, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (280, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (281, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (282, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (283, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (284, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (285, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (286, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (287, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (288, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (289, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (290, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (291, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (292, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (293, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (294, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (295, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (296, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (297, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (298, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (299, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (300, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (301, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (302, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (303, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (304, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (305, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (306, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (307, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (308, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (309, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (310, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (311, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (312, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (313, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (314, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (315, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (316, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (317, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (318, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (319, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (320, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (321, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (322, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (323, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (324, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (325, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (326, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (327, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (328, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (329, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (330, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (331, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (332, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (333, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (334, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (335, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (336, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (337, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (338, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (339, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (340, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (341, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (342, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (343, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (344, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (345, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (346, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (347, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (348, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (349, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (350, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (351, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (352, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (353, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (354, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (355, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (356, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (357, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (358, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (359, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (360, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (361, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (362, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (363, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (364, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (365, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (366, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (367, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (368, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (369, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (370, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (371, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (372, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (373, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (374, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (375, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (376, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (377, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (378, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (379, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (380, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (381, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (382, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (383, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (384, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (385, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (386, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (387, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (388, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (389, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (390, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (391, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (392, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (393, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (394, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (395, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (396, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (397, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (398, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (399, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (400, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (401, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (402, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (403, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (404, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (405, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (406, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (407, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (408, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (409, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (410, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (411, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (412, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (413, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (414, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (415, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (416, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (417, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (418, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (419, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (420, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (421, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (422, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (423, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (424, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (425, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (426, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (427, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (428, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (429, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (430, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (431, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (432, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (433, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (434, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (435, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (436, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (437, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (438, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (439, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (440, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (441, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (442, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (443, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (444, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (445, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (446, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (447, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (448, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (449, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (450, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (451, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (452, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (453, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (454, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (455, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (456, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (457, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (458, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (459, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (460, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (461, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (462, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (463, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (464, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (465, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (466, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (467, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (468, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (469, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (470, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (471, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (472, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (473, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (474, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (475, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (476, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (477, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (478, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (479, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (480, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (481, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (482, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (483, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (484, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (485, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (486, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (487, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (488, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (489, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (490, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (491, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (492, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (493, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (494, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (495, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (496, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (497, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (498, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (499, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (500, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (501, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (502, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (503, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (504, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (505, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (506, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (507, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (508, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (509, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (510, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (511, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (512, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (513, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (514, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (515, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (516, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (517, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (518, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (519, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (520, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (521, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (522, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (523, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (524, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (525, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (526, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (527, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (528, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (529, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (530, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (531, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (532, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (533, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (534, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (535, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (536, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (537, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (538, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (539, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (540, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (541, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (542, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (543, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (544, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (545, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (546, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (547, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (548, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (549, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (550, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (551, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (552, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (553, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (554, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (555, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (556, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (557, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (558, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (559, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (560, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (561, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (562, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (563, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (564, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (565, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (566, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (567, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (568, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (569, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (570, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (571, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (572, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (573, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (574, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (575, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (576, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (577, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (578, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (579, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (580, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (581, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (582, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (583, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (584, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (585, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (586, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (587, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (588, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (589, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (590, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (591, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (592, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (593, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (594, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (595, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (596, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (597, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (598, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (599, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (600, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (601, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (602, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (603, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (604, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (605, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (606, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (607, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (608, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (609, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (610, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (611, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (612, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (613, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (614, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (615, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (616, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (617, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (618, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (619, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (620, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (621, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (622, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (623, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (624, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (625, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (626, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (627, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (628, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (629, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (630, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (631, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (632, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (633, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (634, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (635, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (636, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (637, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (638, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (639, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (640, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (641, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (642, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (643, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (644, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (645, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (646, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (647, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (648, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (649, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (650, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (651, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (652, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (653, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (654, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (655, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (656, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (657, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (658, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (659, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (660, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (661, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (662, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (663, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (664, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (665, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (666, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (667, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (668, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (669, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (670, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (671, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (672, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (673, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (674, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (675, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (676, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (677, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (678, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (679, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (680, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (681, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (682, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (683, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (684, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (685, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (686, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (687, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (688, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (689, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (690, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (691, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (692, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (693, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (694, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (695, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (696, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (697, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (698, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (699, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (700, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (701, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (702, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (703, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (704, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (705, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (706, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (707, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (708, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (709, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (710, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (711, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (712, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (713, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (714, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (715, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (716, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (717, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (718, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (719, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (720, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (721, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (722, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (723, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (724, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (725, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (726, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (727, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (728, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (729, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (730, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (731, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (732, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (733, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (734, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (735, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (736, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (737, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (738, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (739, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (740, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (741, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (742, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (743, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (744, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (745, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (746, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (747, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (748, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (749, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (750, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (751, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (752, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (753, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (754, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (755, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (756, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (757, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (758, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (759, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (760, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (761, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (762, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (763, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (764, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (765, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (766, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (767, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (768, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (769, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (770, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (771, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (772, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (773, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (774, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (775, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (776, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (777, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (778, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (779, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (780, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (781, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (782, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (783, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (784, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (785, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (786, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (787, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (788, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (789, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (790, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (791, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (792, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (793, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (794, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (795, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (796, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (797, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (798, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (799, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (800, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (801, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (802, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (803, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (804, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (805, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (806, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (807, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (808, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (809, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (810, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (811, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (812, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (813, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (814, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (815, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (816, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (817, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (818, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (819, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (820, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (821, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (822, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (823, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (824, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (825, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (826, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (827, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (828, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (829, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (830, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (831, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (832, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (833, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (834, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (835, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (836, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (837, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (838, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (839, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (840, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (841, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (842, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (843, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (844, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (845, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (846, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (847, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (848, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (849, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (850, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (851, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (852, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (853, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (854, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (855, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (856, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (857, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (858, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (859, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (860, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (861, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (862, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (863, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (864, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (865, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (866, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (867, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (868, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (869, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (870, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (871, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (872, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (873, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (874, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (875, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (876, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (877, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (878, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (879, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (880, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (881, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (882, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (883, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (884, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (885, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (886, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (887, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (888, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (889, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (890, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (891, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (892, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (893, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (894, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (895, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (896, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (897, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (898, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (899, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (900, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (901, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (902, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (903, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (904, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (905, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (906, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (907, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (908, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (909, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (910, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (911, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (912, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (913, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (914, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (915, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (916, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (917, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (918, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (919, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (920, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (921, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (922, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (923, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (924, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (925, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (926, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (927, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (928, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (929, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (930, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (931, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (932, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (933, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (934, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (935, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (936, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (937, 'habitación familiar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (938, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (939, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (940, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (941, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (942, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (943, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (944, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (945, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (946, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (947, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (948, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (949, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (950, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (951, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (952, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (953, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (954, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (955, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (956, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (957, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (958, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (959, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (960, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (961, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (962, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (963, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (964, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (965, 'doble');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (966, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (967, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (968, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (969, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (970, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (971, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (972, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (973, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (974, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (975, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (976, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (977, 'habitación con balcón');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (978, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (979, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (980, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (981, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (982, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (983, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (984, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (985, 'habitación con jacuzzi');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (986, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (987, 'habitación de lujo');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (988, 'habitación con piscina privada');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (989, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (990, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (991, 'suite presidencial');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (992, 'habitación con terraza');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (993, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (994, 'habitación ejecutiva');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (995, 'habitación estándar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (996, 'habitación con vista al mar');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (997, 'suite sencilla');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (998, 'habitación temática');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (999, 'habitación con chimenea');
insert into HABITACIONES (numero, tiposhabitacion_nombre) values (1000, 'habitación con chimenea');
