insert into MAQUINAS (maquinas_id, nombre, estado) values (1, 'Máquina de abdominales', 'en reparación');
insert into MAQUINAS (maquinas_id, nombre, estado) values (2, 'Bicicleta estática', 'disponible');
insert into MAQUINAS (maquinas_id, nombre, estado) values (3, 'Bicicleta estática', 'rota');
insert into MAQUINAS (maquinas_id, nombre, estado) values (4, 'Máquina de pesas', 'disponible');
insert into MAQUINAS (maquinas_id, nombre, estado) values (5, 'Máquina de remo', 'en reparación');
insert into MAQUINAS (maquinas_id, nombre, estado) values (6, 'Máquina de remo', 'en mantenimiento');
insert into MAQUINAS (maquinas_id, nombre, estado) values (7, 'Bicicleta estática', 'rota');
insert into MAQUINAS (maquinas_id, nombre, estado) values (8, 'Cinta de correr', 'en mantenimiento');
insert into MAQUINAS (maquinas_id, nombre, estado) values (9, 'Bicicleta estática', 'rota');
insert into MAQUINAS (maquinas_id, nombre, estado) values (10, 'Máquina de remo', 'en mantenimiento');
insert into MAQUINAS (maquinas_id, nombre, estado) values (11, 'Máquina de pesas', 'rota');
insert into MAQUINAS (maquinas_id, nombre, estado) values (12, 'Bicicleta estática', 'en reparación');
insert into MAQUINAS (maquinas_id, nombre, estado) values (13, 'Máquina de pesas', 'fuera de servicio');
insert into MAQUINAS (maquinas_id, nombre, estado) values (14, 'Bicicleta estática', 'en mantenimiento');
insert into MAQUINAS (maquinas_id, nombre, estado) values (15, 'Máquina de abdominales', 'en mantenimiento');
insert into MAQUINAS (maquinas_id, nombre, estado) values (16, 'Máquina de press de piernas', 'rota');
insert into MAQUINAS (maquinas_id, nombre, estado) values (17, 'Máquina de pesas', 'en reparación');
insert into MAQUINAS (maquinas_id, nombre, estado) values (18, 'Cinta de correr', 'rota');
insert into MAQUINAS (maquinas_id, nombre, estado) values (19, 'Cinta de correr', 'disponible');
insert into MAQUINAS (maquinas_id, nombre, estado) values (20, 'Cinta de correr', 'en mantenimiento');
insert into MAQUINAS (maquinas_id, nombre, estado) values (21, 'Máquina de remo', 'en reparación');
insert into MAQUINAS (maquinas_id, nombre, estado) values (22, 'Cinta de correr', 'fuera de servicio');
insert into MAQUINAS (maquinas_id, nombre, estado) values (23, 'Máquina de pesas', 'en reparación');
insert into MAQUINAS (maquinas_id, nombre, estado) values (24, 'Cinta de correr', 'fuera de servicio');
insert into MAQUINAS (maquinas_id, nombre, estado) values (25, 'Máquina de abdominales', 'en mantenimiento');
insert into MAQUINAS (maquinas_id, nombre, estado) values (26, 'Máquina de press de piernas', 'en mantenimiento');
insert into MAQUINAS (maquinas_id, nombre, estado) values (27, 'Máquina de remo', 'disponible');
insert into MAQUINAS (maquinas_id, nombre, estado) values (28, 'Máquina de abdominales', 'disponible');
insert into MAQUINAS (maquinas_id, nombre, estado) values (29, 'Máquina de press de piernas', 'en mantenimiento');
insert into MAQUINAS (maquinas_id, nombre, estado) values (30, 'Máquina de press de piernas', 'fuera de servicio');
insert into MAQUINAS (maquinas_id, nombre, estado) values (31, 'Bicicleta estática', 'en reparación');
insert into MAQUINAS (maquinas_id, nombre, estado) values (32, 'Máquina de pesas', 'en reparación');
insert into MAQUINAS (maquinas_id, nombre, estado) values (33, 'Cinta de correr', 'en reparación');
insert into MAQUINAS (maquinas_id, nombre, estado) values (34, 'Máquina de press de piernas', 'rota');
insert into MAQUINAS (maquinas_id, nombre, estado) values (35, 'Bicicleta estática', 'fuera de servicio');
insert into MAQUINAS (maquinas_id, nombre, estado) values (36, 'Máquina de abdominales', 'en mantenimiento');
insert into MAQUINAS (maquinas_id, nombre, estado) values (37, 'Máquina de press de piernas', 'en mantenimiento');
insert into MAQUINAS (maquinas_id, nombre, estado) values (38, 'Máquina de abdominales', 'en mantenimiento');
insert into MAQUINAS (maquinas_id, nombre, estado) values (39, 'Máquina de remo', 'en reparación');
insert into MAQUINAS (maquinas_id, nombre, estado) values (40, 'Cinta de correr', 'disponible');
insert into MAQUINAS (maquinas_id, nombre, estado) values (41, 'Máquina de remo', 'en reparación');
insert into MAQUINAS (maquinas_id, nombre, estado) values (42, 'Cinta de correr', 'rota');
insert into MAQUINAS (maquinas_id, nombre, estado) values (43, 'Bicicleta estática', 'en mantenimiento');
insert into MAQUINAS (maquinas_id, nombre, estado) values (44, 'Máquina de pesas', 'en mantenimiento');
insert into MAQUINAS (maquinas_id, nombre, estado) values (45, 'Máquina de pesas', 'rota');
insert into MAQUINAS (maquinas_id, nombre, estado) values (46, 'Bicicleta estática', 'en reparación');
insert into MAQUINAS (maquinas_id, nombre, estado) values (47, 'Máquina de pesas', 'disponible');
insert into MAQUINAS (maquinas_id, nombre, estado) values (48, 'Máquina de abdominales', 'en mantenimiento');
insert into MAQUINAS (maquinas_id, nombre, estado) values (49, 'Máquina de pesas', 'en mantenimiento');
insert into MAQUINAS (maquinas_id, nombre, estado) values (50, 'Máquina de press de piernas', 'rota');
insert into MAQUINAS (maquinas_id, nombre, estado) values (51, 'Máquina de abdominales', 'fuera de servicio');
insert into MAQUINAS (maquinas_id, nombre, estado) values (52, 'Máquina de pesas', 'disponible');
insert into MAQUINAS (maquinas_id, nombre, estado) values (53, 'Máquina de remo', 'en reparación');
insert into MAQUINAS (maquinas_id, nombre, estado) values (54, 'Máquina de remo', 'en mantenimiento');
insert into MAQUINAS (maquinas_id, nombre, estado) values (55, 'Bicicleta estática', 'fuera de servicio');
insert into MAQUINAS (maquinas_id, nombre, estado) values (56, 'Máquina de abdominales', 'disponible');
insert into MAQUINAS (maquinas_id, nombre, estado) values (57, 'Máquina de remo', 'disponible');
insert into MAQUINAS (maquinas_id, nombre, estado) values (58, 'Máquina de remo', 'disponible');
insert into MAQUINAS (maquinas_id, nombre, estado) values (59, 'Bicicleta estática', 'rota');
insert into MAQUINAS (maquinas_id, nombre, estado) values (60, 'Cinta de correr', 'en mantenimiento');
insert into MAQUINAS (maquinas_id, nombre, estado) values (61, 'Máquina de remo', 'disponible');
insert into MAQUINAS (maquinas_id, nombre, estado) values (62, 'Máquina de pesas', 'en reparación');
insert into MAQUINAS (maquinas_id, nombre, estado) values (63, 'Máquina de press de piernas', 'en mantenimiento');
insert into MAQUINAS (maquinas_id, nombre, estado) values (64, 'Máquina de remo', 'en reparación');
insert into MAQUINAS (maquinas_id, nombre, estado) values (65, 'Máquina de press de piernas', 'en mantenimiento');
insert into MAQUINAS (maquinas_id, nombre, estado) values (66, 'Máquina de remo', 'disponible');
insert into MAQUINAS (maquinas_id, nombre, estado) values (67, 'Máquina de abdominales', 'en reparación');
insert into MAQUINAS (maquinas_id, nombre, estado) values (68, 'Máquina de press de piernas', 'en mantenimiento');
insert into MAQUINAS (maquinas_id, nombre, estado) values (69, 'Bicicleta estática', 'fuera de servicio');
insert into MAQUINAS (maquinas_id, nombre, estado) values (70, 'Máquina de pesas', 'rota');
insert into MAQUINAS (maquinas_id, nombre, estado) values (71, 'Cinta de correr', 'rota');
insert into MAQUINAS (maquinas_id, nombre, estado) values (72, 'Máquina de pesas', 'fuera de servicio');
insert into MAQUINAS (maquinas_id, nombre, estado) values (73, 'Máquina de pesas', 'rota');
insert into MAQUINAS (maquinas_id, nombre, estado) values (74, 'Bicicleta estática', 'en reparación');
insert into MAQUINAS (maquinas_id, nombre, estado) values (75, 'Bicicleta estática', 'disponible');
insert into MAQUINAS (maquinas_id, nombre, estado) values (76, 'Bicicleta estática', 'en mantenimiento');
insert into MAQUINAS (maquinas_id, nombre, estado) values (77, 'Máquina de pesas', 'disponible');
insert into MAQUINAS (maquinas_id, nombre, estado) values (78, 'Cinta de correr', 'en mantenimiento');
insert into MAQUINAS (maquinas_id, nombre, estado) values (79, 'Máquina de remo', 'en mantenimiento');
insert into MAQUINAS (maquinas_id, nombre, estado) values (80, 'Cinta de correr', 'rota');
insert into MAQUINAS (maquinas_id, nombre, estado) values (81, 'Máquina de pesas', 'en reparación');
insert into MAQUINAS (maquinas_id, nombre, estado) values (82, 'Máquina de press de piernas', 'rota');
insert into MAQUINAS (maquinas_id, nombre, estado) values (83, 'Máquina de abdominales', 'en mantenimiento');
insert into MAQUINAS (maquinas_id, nombre, estado) values (84, 'Máquina de press de piernas', 'disponible');
insert into MAQUINAS (maquinas_id, nombre, estado) values (85, 'Máquina de remo', 'disponible');
insert into MAQUINAS (maquinas_id, nombre, estado) values (86, 'Bicicleta estática', 'disponible');
insert into MAQUINAS (maquinas_id, nombre, estado) values (87, 'Máquina de pesas', 'rota');
insert into MAQUINAS (maquinas_id, nombre, estado) values (88, 'Bicicleta estática', 'en reparación');
insert into MAQUINAS (maquinas_id, nombre, estado) values (89, 'Máquina de abdominales', 'disponible');
insert into MAQUINAS (maquinas_id, nombre, estado) values (90, 'Bicicleta estática', 'fuera de servicio');
insert into MAQUINAS (maquinas_id, nombre, estado) values (91, 'Cinta de correr', 'en mantenimiento');
insert into MAQUINAS (maquinas_id, nombre, estado) values (92, 'Máquina de press de piernas', 'en mantenimiento');
insert into MAQUINAS (maquinas_id, nombre, estado) values (93, 'Máquina de remo', 'disponible');
insert into MAQUINAS (maquinas_id, nombre, estado) values (94, 'Bicicleta estática', 'rota');
insert into MAQUINAS (maquinas_id, nombre, estado) values (95, 'Máquina de abdominales', 'disponible');
insert into MAQUINAS (maquinas_id, nombre, estado) values (96, 'Máquina de abdominales', 'en mantenimiento');
insert into MAQUINAS (maquinas_id, nombre, estado) values (97, 'Máquina de remo', 'en reparación');
insert into MAQUINAS (maquinas_id, nombre, estado) values (98, 'Cinta de correr', 'disponible');
insert into MAQUINAS (maquinas_id, nombre, estado) values (99, 'Máquina de abdominales', 'fuera de servicio');
insert into MAQUINAS (maquinas_id, nombre, estado) values (100, 'Bicicleta estática', 'en mantenimiento');
