--RFC1 - MOSTRAR EL DINERO RECOLECTADO POR SERVICIOS EN CADA HABITACIÓN EN EL ÚLTIMO AÑO CORRIDO



--RFC2 - MOSTRAR LOS 20 SERVICIOS MÁS POPULARES



--RFC3 - MOSTRAR EL ÍNDICE DE OCUPACIÓN DE CADA UNA DE LAS HABITACIONES DEL HOTEL



--RFC4 - MOSTRAR LOS SERVICIOS QUE CUMPLEN CON CIERTA CARACTERÍSTICA



--RFC5 - MOSTRAR EL CONSUMO EN HOTELANDES POR UN USUARIO DADO, EN UN RANGO DE FECHAS INDICADO



--RFC6 - ANALIZAR LA OPERACIÓN DE HOTELANDES



--RFC7 - ENCONTRAR LOS BUENOS CLIENTES



--RFC8 - ENCONTRAR LOS SERVICIOS QUE NO TIENEN MUCHA DEMANDA



--RFC9 - CONSULTAR CONSUMO EN HOTELANDES



--RFC10 - CONSULTAR CONSUMO EN HOTELANDES – RFC9-V2



--RFC11 - CONSULTAR FUNCIONAMIENTO



--RFC12 - CONSULTAR LOS CLIENTES EXCELENTES


